#define SMM_HANDLER_OFFSET	0x8000
#define SMM_ADDR_START		0xaff00000
#define SMM_TSEG_SIZE		0x100000
#define SMM_STACK_START_T	(SMM_ADDR_START + SMM_TSEG_SIZE - SMM_HANDLER_OFFSET)
#define SMM_STACK_START		(SMM_ADDR_START + SMM_TSEG_SIZE - SMM_HANDLER_OFFSET)
#define SMM_REAL_START		(SMM_STACK_START + 0x1000)
